landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name = 'index'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.books, name='books'),
    path('search_books/<str:param>/', views.search_books, name="search_books"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.user, name='user'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

landingpage/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story8/forms.py
from django import forms

class Search_Box(forms.Form):
    Search_Box = forms.CharField(label="", widget=forms.TextInput(attrs={'class': "form-control"}))

landingpage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    response = {

    }

    return render(request, 'index.html', response)

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
from .forms import Search_Box

# Create your views here.
def books(request):
    response = {
        'form': Search_Box
    }

    return render(request, 'books.html', response)

def search_books(request, param):
    json = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + param).json()
    return JsonResponse(json)

story9/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.
def user(request):
    return render(request, 'user.html')

def login(request):
    if request.user is not None:
        if request.user.is_authenticated:
            return redirect('story9:user')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            request.session['login_timestamp'] = str(datetime.now())
            return redirect('story9:user')
        else:
            return render(request, 'login.html', {
                'error' : True
            })        

    return render(request, 'login.html')

def logout(request):
    request.session.flush()
    auth_logout(request)
    return redirect('story9:user')

landingpage/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link id="style" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>Story 7 - Abi Fajri</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <span>
            <a class="navbar-brand" href="{% url 'landingpage:index' %}">
                abi<span class="color-2">fajri</span>
            </a>
            <hr class="hr-navbrand">
        </span>
        
        <div id="nav-switch-button">
            <span class="navbar-text">
                Light
            </span>

            <label class="switch">
                <input id="light-switch" type="checkbox">
                <span class="slider round"></span>
            </label>

            <span class="navbar-text">
                Dark
            </span>
        </div>

    </nav>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4" id="profile">
                <img class="my-pict" src="{% static 'img/my-pict.jpg' %}">
                <br><br>
                <p>
                    Hi <span class="color-2">there!</span>
                    <br>
                    I love to play <span class="color-2">video games</span>,
                    <br>
                    watch <span class="color-2">movies</span>, and <span class="color-2">schleep</span>!
                </p>
            </div>

            <div class="col-sm-1">
                <div class="v-line1"></div>
            </div>

            <div class="col-sm-1">
                <div class="v-line2"></div>
            </div>

            <div class="col-sm-6" id="about">
                <h3 style="font-weight: bold; margin-bottom: 20px;">About me</h3>

                <button class="accordion">Who am I?</button>
                <div class="panel">
                    <p>My name is Abi Fajri Abdillah, a man with a big goal to change the world!</p>
                </div>

                <button class="accordion">What am I doing right now?</button>
                <div class="panel">
                    <p>I'm currently studying at University of Indonesia, and my major is Computer Science.</p>
                </div>

                <button class="accordion">Is there any organization/committee that I joined?</button>
                <div class="panel">
                    <p>Soon to be filled!</p>
                </div>

                <button class="accordion">Is there any achievement I've achieved?</button>
                <div class="panel">
                    <p>None at the moment, but it'll be filled in the near future!</p>
                </div>

                <button class="accordion">What is my favorite things to do?</button>
                <div class="panel">
                    <p>I really love to play video games. Even I want to be a <i>good</i> game designer in the future!
                        My second most favorite is watching movies and sleep. Yes, sleep is good!</p>
                </div>
            </div>
        </div>
    </div>

    <hr class="hr-long">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
        </script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

story8/templates/books.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link id="style" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>Story 8 - Abi Fajri</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <span>
            <a class="navbar-brand" href="{% url 'landingpage:index' %}">
                abi<span class="color-2">fajri</span>
            </a>
            <hr class="hr-navbrand">
        </span>
    </nav>
    <br>

    <div class="container">
        <h2 style="text-align: center; font-weight: bold;">Search Books</h2>
        <form id="searchBooks" action="" method="GET">
            {% csrf_token %}
            {{form}}
        </form>
    </div>

    <div class="container">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Author</th>
                    <th scope="col">More</th>
                    </tr>
                </thead>
                <tbody class="body"></tbody>
            </table> 
    </div>

    <hr class="hr-long">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
        </script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/books.js' %}"></script>
</body>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link id="style" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>Story 9 (Login) - Abi Fajri</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <span>
            <a class="navbar-brand" href="{% url 'landingpage:index' %}">
                abi<span class="color-2">fajri</span>
            </a>
            <hr class="hr-navbrand">
        </span>
    </nav>
    <br>

    <div class="container">
        <h2 style="text-align: center; font-weight: bold; margin: 10px;">Log In</h2>
        {% if error %}
            <div class="alert alert-danger">
                Invalid Username/Password!
            </div> 
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label>Username</label>
                <input type="text" class="form-control" placeholder="Username" name="username">
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" placeholder="Password" name="password">
            </div>
            <button type="submit" class="btn btn-outline-info">Submit</button>
        </form>
    </div>

    <hr class="hr-long">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

story9/templates/user.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link id="style" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>Story 9 - Abi Fajri</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <span>
            <a class="navbar-brand" href="{% url 'landingpage:index' %}">
                abi<span class="color-2">fajri</span>
            </a>
            <hr class="hr-navbrand">
        </span>
    </nav>
    <br><br><br><br><br><br>

    <div class="container">
        {% if user.is_authenticated %}
        <h3 style="text-align: center; font-weight: bold;">
            Hello, {{user.first_name}} {{user.last_name}}!
            <br>
        </h3>
        <br>
        <div style="text-align: center;">
            <small>Logged in at {{request.session.login_timestamp}}</small>
        </div>
        <br>
        <div style="text-align: center;">
            <a class="btn btn-outline-info" href="{% url 'story9:logout' %}">Logout</a>
        </div>
        {% else %}
        <h3 style="text-align: center; font-weight: bold;">
            Please Log In.
            <br>
        </h3>
        <br>
        <div style="text-align: center;">
            <a class="btn btn-outline-info" href="{% url 'story9:login' %}">Login</a>
        </div>
        {% endif %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>